### ISSUE TITLE
App crashes on start under Android 6.0

### ISSUE THREAD

**Issue by stevenmirabito** [Z-KO/CSH-Android-Drink#10]
Under Android 6.0, the app will crash once the user enters their API key, and will crash immediately on subsequent launches (as the app is reading the API key from securestorage). This is due to a [bug in the Gson library](https://github.com/google/gson/issues/648), which has not yet been resolved.

Logcat:

```
10-08 16:54:37.542: I/ActivityManager(2039): Displayed edu.csh.androiddrink/.activities.MainActivity: +538ms (total +664ms)
10-08 16:54:37.544: E/AndroidRuntime(751): FATAL EXCEPTION: AsyncTask #1
10-08 16:54:37.544: E/AndroidRuntime(751): Process: edu.csh.androiddrink, PID: 751
10-08 16:54:37.544: E/AndroidRuntime(751): java.lang.RuntimeException: An error occurred while executing doInBackground()
10-08 16:54:37.544: E/AndroidRuntime(751):  at android.os.AsyncTask$3.done(AsyncTask.java:309)
10-08 16:54:37.544: E/AndroidRuntime(751):  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
10-08 16:54:37.544: E/AndroidRuntime(751):  at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
10-08 16:54:37.544: E/AndroidRuntime(751):  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
10-08 16:54:37.544: E/AndroidRuntime(751):  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-08 16:54:37.544: E/AndroidRuntime(751):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-08 16:54:37.544: E/AndroidRuntime(751):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-08 16:54:37.544: E/AndroidRuntime(751):  at java.lang.Thread.run(Thread.java:818)
10-08 16:54:37.544: E/AndroidRuntime(751): Caused by: java.lang.SecurityException: Can't make field constructor accessible
10-08 16:54:37.544: E/AndroidRuntime(751):  at java.lang.reflect.Constructor.setAccessible(Constructor.java:334)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.ConstructorConstructor.newDefaultConstructor(ConstructorConstructor.java:97)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:79)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:82)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.Gson.getAdapter(Gson.java:359)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.MapTypeAdapterFactory.getKeyAdapter(MapTypeAdapterFactory.java:140)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:125)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.Gson.getAdapter(Gson.java:359)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:122)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:46)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:92)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:91)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:142)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.Gson.getAdapter(Gson.java:359)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:122)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:46)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:92)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:91)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:142)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.Gson.getAdapter(Gson.java:359)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create(CollectionTypeAdapterFactory.java:52)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.Gson.getAdapter(Gson.java:359)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:122)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:46)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:92)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:91)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:142)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:83)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.Gson.getAdapter(Gson.java:359)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:122)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:46)
10-08 16:54:37.544: E/AndroidRuntime(751):  at com.google.gson.internal.bind.R
10-08 16:54:37.546: W/ActivityManager(2039):   Force finishing activity edu.csh.androiddrink/.activities.MainActivity
10-08 16:54:37.635: I/Process(751): Sending signal. PID: 751 SIG: 9
10-08 16:54:37.637: I/OpenGLRenderer(2039): Initialized EGL, version 1.4
10-08 16:54:37.639: E/lowmemorykiller(281): Error writing /proc/751/oom_score_adj; errno=22
10-08 16:54:37.722: D/GraphicsStats(2039): Buffer count: 18
10-08 16:54:37.723: I/WindowState(2039): WIN DEATH: Window{add6868 u0 edu.csh.androiddrink/edu.csh.androiddrink.activities.MainActivity}
10-08 16:54:37.733: I/ActivityManager(2039): Process edu.csh.androiddrink (pid 751) has died
```

**Comment by zujko** [comment]
I'm currently doing a full rewrite of the app so I'll hold off on merging your pull request until I get most of that completed.
